CREATE TABLE notifications (
                             id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                             title TEXT,
                             body TEXT,
                             token TEXT,
                             notification_type VARCHAR(30)
);