CREATE TABLE coordinates (
                             id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                             longitude DOUBLE PRECISION NOT NULL,
                             latitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE locations (
                           id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                           coordinates_id BIGINT REFERENCES coordinates(id),
                           municipality VARCHAR(250) NOT NULL,
                           address VARCHAR(250) NOT NULL
);

CREATE TABLE users (
                            id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                            first_name VARCHAR(100) NOT NULL,
                            last_name VARCHAR(100) NOT NULL,
                            email VARCHAR(250) NOT NULL,
                            password VARCHAR(100) NOT NULL,
                            user_type VARCHAR(30) NOT NULL,
                            phone_number VARCHAR(100),
                            activated BOOLEAN NOT NULL
);

CREATE TABLE lost_pets (
                           id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(100),
                           pet_type VARCHAR(30),
                           photo VARCHAR(255),
                           additional_information VARCHAR(255),
                           pet_owner_id BIGINT REFERENCES users(id),
                           lost_at_time TIMESTAMP,
                           lost_at_location_id BIGINT REFERENCES locations(id),
                           status VARCHAR(30)
);

CREATE TABLE seen_pets (
                           id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                           lost_pet_id BIGINT REFERENCES lost_pets(id),
                           seen_at_time TIMESTAMP,
                           seen_at_location_id BIGINT REFERENCES locations(id),
                           reported_by_id BIGINT REFERENCES users(id)
);