CREATE TABLE messages (
                             id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                             sender_id BIGINT REFERENCES users(id),
                             recipient_id BIGINT REFERENCES users(id),
                             content TEXT,
                             sent_at TIMESTAMP
);